openapi: 3.0.3
info:
  title: PKKA Backend API
  description: REST API for the Alumni Club platform of the AGH Faculty of Computer Science.
  version: v1
paths:
  /api/announcements:
    get:
      summary: Pobiera listę ogłoszeń
      operationId: getAnnouncements
      responses:
        "200":
          description: Lista ogłoszeń pobrana pomyślnie
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Announcement"

components:
  schemas:
    Author:
      type: object
      required:
        - name
        - role
      properties:
        name:
          type: string
          x-faker: person.fullName
        role:
          type: string
          x-faker: person.jobTitle
        avatarUrl:
          type: string
          x-faker: image.avatar

    Announcement:
      type: object
      required:
        - id
        - title
        - description
        - content
        - date
        - time
        - tag
        - imageUrl
        - slug
        - author
      properties:
        id:
          type: string
          description: Unikalne ID ogłoszenia
        title:
          type: string
          description: Tytuł ogłoszenia
        description:
          type: string
          description: Krótki opis (zajawka na liście ogłoszeń)
          x-faker: lorem.sentence
        content:
          type: string
          description: Pełna treść ogłoszenia z akapitami
          x-faker: lorem.paragraphs
        date:
          type: string
          description: Data w formacie tekstowym (np. 10 maja 2026)
        time:
          type: string
          description: Godzina publikacji (np. 14:30)
        tag:
          type: string
          description: Kategoria (np. Wydarzenie, Warsztaty)
        imageUrl:
          type: string
          description: Ścieżka do obrazka
        slug:
          type: string
          description: Przyjazny URL
        author:
          $ref: "#/components/schemas/Author"
