ALTER TABLE users
    ADD COLUMN email        VARCHAR(255),
    ADD COLUMN discord_id   VARCHAR(32),
    ADD COLUMN show_name    BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN show_email   BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN show_discord BOOLEAN NOT NULL DEFAULT TRUE;
